CREATE SCHEMA 'iot' DEFAULT CHARACTER SET utf8 ;

CREATE TABLE HOUSEREGION
(
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
)

CREATE TABLE HOUSEDEVICE
(
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ADDRESS VARCHAR(255) NOT NULL,
    STATE INTEGER NOT NULL,
    DEVICETYPE INTEGER NOT NULL,
    UUID VARCHAR(50) NOT NULL
)

CREATE TABLE HOUSECONTROLLER
(
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    STATE INTEGER NOT NULL,
    PORT INTEGER NOT NULL,
    IDREGION INTEGER NOT NULL,
    IDDEVICE INTEGER NOT NULL,
    CONSTRAINT FK_CONTROLLER_REGION FOREIGN KEY (IDREGION) REFERENCES HOUSEREGION (ID)    
    CONSTRAINT FK_CONTROLLER_DEVICE FOREIGN KEY (IDDEVICE) REFERENCES HOUSEDEVICE (ID)
);


CREATE TABLE item
(
    id BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);
CREATE TABLE journal
(
    id BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    publish_date DATETIME NOT NULL,
    uuid VARCHAR(255),
    publisher_id BIGINT(20) NOT NULL,
    CONSTRAINT FK_c7picib39dl7kxro2349cnpn9 FOREIGN KEY (publisher_id) REFERENCES publisher (id)
);
CREATE INDEX FK_c7picib39dl7kxro2349cnpn9 ON journal (publisher_id);
CREATE TABLE publisher
(
    id BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    user_id BIGINT(20) NOT NULL,
    CONSTRAINT FK_ml1xc0aovqkkm2p1lssgjkfas FOREIGN KEY (user_id) REFERENCES user (id)
);
CREATE UNIQUE INDEX UK_ml1xc0aovqkkm2p1lssgjkfas ON publisher (user_id);
CREATE TABLE subscription
(
    id BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    date DATETIME NOT NULL,
    user_id BIGINT(20) NOT NULL
);
CREATE UNIQUE INDEX UK_tq3cq3gmsss8jjyb2l5sb1o6k ON subscription (user_id);