CREATE SCHEMA 'iot' DEFAULT CHARACTER SET utf8 ;

CREATE TABLE HOUSECONTROLLER
(
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
)

CREATE TABLE HOUSEDEVICE
(
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ADDRESS VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    STATE INTEGER NOT NULL,
    DEVICETYPE INTEGER NOT NULL,
    UUID VARCHAR(50) NOT NULL
)

CREATE TABLE HOUSECOMPONENT
(
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PORT INTEGER NOT NULL,
    IDCONTROLLER INTEGER NOT NULL,
    IDDEVICE INTEGER NOT NULL,
    CONSTRAINT FK_COMPONENT_CONTROLLER FOREIGN KEY (IDCONTROLLER) REFERENCES HOUSECONTROLLER (ID)    
    CONSTRAINT FK_COMPONENT_DEVICE FOREIGN KEY (IDDEVICE) REFERENCES HOUSEDEVICE (ID)
);
